In [ ]:
import pandas as pd
from scipy.special import comb
import ast

In [ ]:
def upperTailProb(n, k):
    prob = 0
    for i in range(k, n + 1):
        choose = comb(n, i, exact=True)
        prob += choose * (0.5 ** n)
    return prob

def lowerTailProb(n, k):
    prob = 0
    for i in range(0, k + 1):
        choose = comb(n, i, exact=True)
        prob += choose * (0.5 ** n)
    return prob

def goatScore(n, k):
    prob = upperTailProb(n, k)
    return 1 / prob if prob > 0 else float('inf')

def woatScore(n, k):
    prob = lowerTailProb(n, k)
    return 1 / prob if prob > 0 else float('inf')

In [47]:
df = pd.read_csv("../data/processed/mlb&nba.csv")

df['Sequence_Numeric'] = df['Sequence'].apply(ast.literal_eval)
df['Wins'] = df['Sequence_Numeric'].apply(sum)
df['Games_Played'] = df['Sequence_Numeric'].apply(len)

In [51]:
df['GOAT_Score'] = df.apply(lambda row: goatScore(row['Games_Played'], row['Wins']), axis = 1)

df['WOAT_Score'] = df.apply(lambda row: woatScore(row['Games_Played'], row['Wins']), axis = 1)
df.head(1)

,Unnamed: 0,League,Season,Team,Sequence,Sequence_Numeric,Wins,Games_Played,GOAT_Score,WOAT_Score
0,0,MLB,1926,Boston Red Sox,"[0,1,0,1,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0...","[0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, ...",46,153,1.0,2.239271e+06

In [54]:
output = "../data/processed/us_leagues_binomial.csv"

out = df[['League', 'Season', 'Team', 'Sequence', 'GOAT_Score', 'WOAT_Score']]

out.to_csv(output)

In [45]:
df_NBA = df[df["League"] == "NBA"]

df_MLB = df[df["League"] == "MLB"]

In [44]:
df_NBA.nlargest(10, "GOAT_Score")[["Team", "Season", "League", "GOAT_Score"]]

                       Team  Season League    GOAT_Score
3133          Chicago Bulls    1995    NBA  1.956068e+12
2850          Chicago Bulls    1996    NBA  8.865848e+09
2528  Oklahoma City Thunder    2024    NBA  1.762217e+09
2365  Golden State Warriors    2016    NBA  3.804222e+08
2604     Los Angeles Lakers    1999    NBA  3.804222e+08
2714         Boston Celtics    1985    NBA  3.804222e+08
2950       Dallas Mavericks    2006    NBA  3.804222e+08
2987  Golden State Warriors    2014    NBA  3.804222e+08
3454          Chicago Bulls    1991    NBA  3.804222e+08
2330         Boston Celtics    2007    NBA  8.881075e+07

In [46]:
df_MLB.nlargest(10, "GOAT_Score")[["Team", "Season", "League", "GOAT_Score"]]

                        Team  Season League    GOAT_Score
1580        Seattle Mariners    2001    MLB  5.449882e+07
454        Cleveland Indians    1954    MLB  4.905777e+07
25          New York Yankees    1927    MLB  1.907257e+07
1484        New York Yankees    1998    MLB  8.867464e+06
90    Philadelphia Athletics    1931    MLB  3.780815e+06
217         New York Yankees    1939    MLB  2.668802e+06
105         New York Yankees    1932    MLB  1.887978e+06
58    Philadelphia Athletics    1929    MLB  8.091980e+05
2199     Los Angeles Dodgers    2022    MLB  7.208491e+05
270      St. Louis Cardinals    1942    MLB  5.903959e+05