In [9]:
import pandas as pd
from scipy.special import comb
import ast

In [10]:
def upperTailProb(n, k):
    prob = 0
    for i in range(k, n + 1):
        choose = comb(n, i, exact=True)
        prob += choose * (0.5 ** n)
    return prob

def lowerTailProb(n, k):
    prob = 0
    for i in range(0, k + 1):
        choose = comb(n, i, exact=True)
        prob += choose * (0.5 ** n)
    return prob

def goatScore(n, k):
    prob = upperTailProb(n, k)
    return 1 / prob if prob > 0 else float('inf')

def woatScore(n, k):
    prob = lowerTailProb(n, k)
    return 1 / prob if prob > 0 else float('inf')

In [11]:
df = pd.read_csv("../data/processed/us_leagues.csv")

df['Sequence_Numeric'] = df['Sequence'].apply(ast.literal_eval)
df['Wins'] = df['Sequence_Numeric'].apply(sum)
df['Games_Played'] = df['Sequence_Numeric'].apply(len)

In [12]:
df['GOAT_Score'] = df.apply(lambda row: goatScore(row['Games_Played'], row['Wins']), axis = 1)

df['WOAT_Score'] = df.apply(lambda row: woatScore(row['Games_Played'], row['Wins']), axis = 1)
df.head(1)

,League,Season,Team,Sequence,Sequence_Numeric,Wins,Games_Played,GOAT_Score,WOAT_Score
0,NBA,2015,Orlando Magic,"[0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, ...","[0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, ...",35,82,1.081476,8.918835

In [13]:
output = "../output/csvs/us_leagues_goat_scores.csv"

out = df[['League', 'Season', 'Team', 'Sequence', 'GOAT_Score', 'WOAT_Score']]

out.to_csv(output)

In [14]:
df_NBA = df[df["League"] == "NBA"]

df_MLB = df[df["League"] == "MLB"]

In [15]:
df_NBA.nlargest(10, "GOAT_Score")[["Team", "Season", "League", "GOAT_Score"]]

                       Team  Season League    GOAT_Score
6     Golden State Warriors    2015    NBA  1.452710e+13
3163          Chicago Bulls    1995    NBA  1.956068e+12
3680     Los Angeles Lakers    1971    NBA  1.250222e+10
4092     Los Angeles Lakers    1971    NBA  1.250222e+10
2880          Chicago Bulls    1996    NBA  8.865848e+09
3604     Philadelphia 76ers    1966    NBA  7.542284e+09
4016     Philadelphia 76ers    1966    NBA  7.542284e+09
2558  Oklahoma City Thunder    2024    NBA  1.762217e+09
3665        Milwaukee Bucks    1970    NBA  1.044185e+09
4077        Milwaukee Bucks    1970    NBA  1.044185e+09

In [16]:
df_MLB.nlargest(10, "GOAT_Score")[["Team", "Season", "League", "GOAT_Score"]]

                        Team  Season League    GOAT_Score
1610        Seattle Mariners    2001    MLB  5.449882e+07
484        Cleveland Indians    1954    MLB  4.905777e+07
55          New York Yankees    1927    MLB  1.907257e+07
1514        New York Yankees    1998    MLB  8.867464e+06
120   Philadelphia Athletics    1931    MLB  3.780815e+06
247         New York Yankees    1939    MLB  2.668802e+06
135         New York Yankees    1932    MLB  1.887978e+06
88    Philadelphia Athletics    1929    MLB  8.091980e+05
2229     Los Angeles Dodgers    2022    MLB  7.208491e+05
300      St. Louis Cardinals    1942    MLB  5.903959e+05